### ISSUE TITLE
MIT license? - https://help.github.com/en/articles/adding-a-license-to-a-repository

### ISSUE THREAD

**Issue by blairanderson** [mattxgreen/amazonFBACalc#1]
Hi There, i noticed there's no license on this project. 

https://help.github.com/en/articles/adding-a-license-to-a-repository

would be cool if you added MIT

**Comment by mattxgreen** [comment]
Yeah, MIT is fine. It's free for use/modification etc.

**Comment by mattxgreen** [comment]
...actually I just checked the package.json, and MIT is in there.
